{"name": "Test - Validar la creación de una minuta", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=137.0.7151.68)\nStacktrace:\n#0 0x5d0ac11fe7fa <unknown>\n#1 0x5d0ac0ca2ce3 <unknown>\n#2 0x5d0ac0cf5a7e <unknown>\n#3 0x5d0ac0ce897d <unknown>\n#4 0x5d0ac0d1a242 <unknown>\n#5 0x5d0ac0ce82fa <unknown>\n#6 0x5d0ac0d1a40e <unknown>\n#7 0x5d0ac0d40135 <unknown>\n#8 0x5d0ac0d1a013 <unknown>\n#9 0x5d0ac0ce6b3b <unknown>\n#10 0x5d0ac0ce77a1 <unknown>\n#11 0x5d0ac11c3b9b <unknown>\n#12 0x5d0ac11c7a8a <unknown>\n#13 0x5d0ac11ab912 <unknown>\n#14 0x5d0ac11c8604 <unknown>\n#15 0x5d0ac119074f <unknown>\n#16 0x5d0ac11ec678 <unknown>\n#17 0x5d0ac11ec856 <unknown>\n#18 0x5d0ac11fd666 <unknown>\n#19 0x7e820f29caa4 <unknown>\n#20 0x7e820f329c3c <unknown>\n\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/WhenDefinition.py\", line 40, in step_impl\n    context.elements._implicity_wait(int(os.getenv(\"IMPLICITY_WAIT\")),\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 404, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Estoy en el ingreso al portal sin loguearme", "status": "passed", "attachments": [{"name": "screenshot", "source": "09fb1a97-6348-429a-8cd6-2af01853b0c3-attachment.png", "type": "image/png"}], "start": 1750275125704, "stop": 1750275129726}, {"name": "When Me logueo con las credenciales \"admin\"", "status": "passed", "attachments": [{"name": "screenshot", "source": "a42aff2c-e69c-4433-9e52-5e071584f5bf-attachment.png", "type": "image/png"}], "start": 1750275129726, "stop": 1750275135965}, {"name": "And Despliego la seccion \"Risk Management\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=137.0.7151.68)\nStacktrace:\n#0 0x5d0ac11fe7fa <unknown>\n#1 0x5d0ac0ca2ce3 <unknown>\n#2 0x5d0ac0cf5a7e <unknown>\n#3 0x5d0ac0ce897d <unknown>\n#4 0x5d0ac0d1a242 <unknown>\n#5 0x5d0ac0ce82fa <unknown>\n#6 0x5d0ac0d1a40e <unknown>\n#7 0x5d0ac0d40135 <unknown>\n#8 0x5d0ac0d1a013 <unknown>\n#9 0x5d0ac0ce6b3b <unknown>\n#10 0x5d0ac0ce77a1 <unknown>\n#11 0x5d0ac11c3b9b <unknown>\n#12 0x5d0ac11c7a8a <unknown>\n#13 0x5d0ac11ab912 <unknown>\n#14 0x5d0ac11c8604 <unknown>\n#15 0x5d0ac119074f <unknown>\n#16 0x5d0ac11ec678 <unknown>\n#17 0x5d0ac11ec856 <unknown>\n#18 0x5d0ac11fd666 <unknown>\n#19 0x7e820f29caa4 <unknown>\n#20 0x7e820f329c3c <unknown>\n\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/WhenDefinition.py\", line 40, in step_impl\n    context.elements._implicity_wait(int(os.getenv(\"IMPLICITY_WAIT\")),\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 404, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "57d0314a-9dd2-459c-9e7d-ba37379bce1d-attachment.png", "type": "image/png"}], "start": 1750275135965, "stop": 1750275163981}, {"name": "And Me dirijo a la seccion \"Approval Minutes\"", "status": "skipped", "start": 1750275164036, "stop": 1750275164036}, {"name": "And Presiono el boton \"New\"", "status": "skipped", "start": 1750275164036, "stop": 1750275164036}], "start": 1750275124404, "stop": 1750275164036, "uuid": "4d82dd3e-56f8-4161-a51d-e4f46d06ffd0", "historyId": "8906f859fcb4190f65985eea78534515", "fullName": "Risks: Test - Validar la creación de una minuta", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "create_minute"}, {"name": "tag", "value": "regresion"}, {"name": "tag", "value": "risks"}, {"name": "feature", "value": "Risks"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}