{"name": "Test - Validar la finalizacion de una solucitud", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=46267): Max retries exceeded with url: /session/97972f3135089095e46251e8cf21f42a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x747c42261fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 56, in after_step\n    pm.hook.after_step(context=context, step=step)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ipadula/Avla/helper/plugins/SeleniumPlugin.py\", line 187, in after_step\n    allure.attach(context.browser.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given Estoy en el ingreso al portal sin loguearme", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=46267): Max retries exceeded with url: /session/97972f3135089095e46251e8cf21f42a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x747c42261fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 56, in after_step\n    pm.hook.after_step(context=context, step=step)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ipadula/Avla/helper/plugins/SeleniumPlugin.py\", line 187, in after_step\n    allure.attach(context.browser.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1750274340852, "stop": 1750274343855}, {"name": "When Me logueo con las credenciales \"admin\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "When Despliego la seccion \"Bond/Surety Management\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Me dirijo a la seccion \"Requests\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono el boton \"New\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Selecciono en \"1st Digit Code\" \"6 - Federal\" en \"General data\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Selecciono en \"Class Description\" \"Bid or Proposal Bonds\" en \"General data\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Selecciono en \"2nd & 3rd Digit Code\" \"0\" en \"General data\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Selecciono en \"Principal\" \"174-54-3118\" en \"Contractor information\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Selecciono en \"Insured\" \"155\" en \"Obligees Information\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Agrego un \"Bid Contract Amount\" \"1000\" en \"Job description\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono \"Add\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono \"Save\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono \"Yes\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Guardo el numero de Request", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Me dirijo a la seccion \"Requests\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Busco la solicitud previamente creada", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono el boton para buscar", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono \"Visualize\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono \"Add\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343862}, {"name": "And Presiono \"Finish Registration\"", "status": "skipped", "start": 1750274343862, "stop": 1750274343863}, {"name": "And Presiono \"Yes\"", "status": "skipped", "start": 1750274343863, "stop": 1750274343863}], "start": 1750274337861, "stop": 1750274343863, "uuid": "e83a04a5-80ab-46ea-adaf-e4e3f76456ee", "historyId": "d32e639c33be86608ea3371e0dde5f6b", "fullName": "Bond/Surety Management: Test - Validar la finalizacion de una solucitud", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "bond"}, {"name": "tag", "value": "end"}, {"name": "tag", "value": "regresion"}, {"name": "tag", "value": "requests"}, {"name": "feature", "value": "Bond/Surety Management"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}